// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using SentinelApi.Infrastructure.Persistence.Context;

#nullable disable

namespace SentinelApi.Infrastructure.Migrations
{
    [DbContext(typeof(SentinelDbContext))]
    [Migration("20260604013953_AddUidFirebase")]
    partial class AddUidFirebase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SentinelApi.Domain.Entities.Regiao", b =>
                {
                    b.Property<int>("IdRegiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_REGIAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRegiao"));

                    b.Property<string>("NmEstado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_ESTADO");

                    b.Property<string>("NmPais")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NM_PAIS");

                    b.Property<string>("NmRegiao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NM_REGIAO");

                    b.Property<decimal>("ReLatitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("DECIMAL(10,6)")
                        .HasColumnName("RE_LATITUDE");

                    b.Property<decimal>("ReLongitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("DECIMAL(10,6)")
                        .HasColumnName("RE_LONGITUDE");

                    b.HasKey("IdRegiao");

                    b.ToTable("T_SEN_REGIAO", (string)null);
                });

            modelBuilder.Entity("SentinelApi.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ID_USUARIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ATIVO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("EMAIL");

                    b.Property<string>("FcmToken")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("NVARCHAR2(500)")
                        .HasColumnName("FCM_TOKEN");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("DECIMAL(10,6)")
                        .HasColumnName("LATITUDE");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("DECIMAL(10,6)")
                        .HasColumnName("LONGITUDE");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<int>("RaioKm")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("RAIO_KM");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("SENHA_HASH");

                    b.Property<string>("UidFirebase")
                        .HasMaxLength(128)
                        .HasColumnType("NVARCHAR2(128)")
                        .HasColumnName("UID_FIREBASE");

                    b.HasKey("IdUsuario");

                    b.ToTable("T_SEN_USUARIO", (string)null);
                });

            modelBuilder.Entity("SentinelApi.Domain.Entities.UsuarioRegiao", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("T_SEN_USUARIO_ID_USUARIO");

                    b.Property<int>("IdRegiao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("T_SEN_REGIAO_ID_REGIAO");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("US_RE_ATIVO");

                    b.Property<DateTime>("DataInscricao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_INSCRICAO");

                    b.HasKey("IdUsuario", "IdRegiao");

                    b.HasIndex("IdRegiao");

                    b.ToTable("T_SEN_USUARIO_REGIAO", (string)null);
                });

            modelBuilder.Entity("SentinelApi.Domain.Entities.UsuarioRegiao", b =>
                {
                    b.HasOne("SentinelApi.Domain.Entities.Regiao", "Regiao")
                        .WithMany("UsuarioRegioes")
                        .HasForeignKey("IdRegiao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SentinelApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRegioes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Regiao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SentinelApi.Domain.Entities.Regiao", b =>
                {
                    b.Navigation("UsuarioRegioes");
                });

            modelBuilder.Entity("SentinelApi.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("UsuarioRegioes");
                });
#pragma warning restore 612, 618
        }
    }
}
